name: Test

on: [ push, pull_request ]

jobs:
  run-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      matrix: &matrix
        php: [ 8.1, 8.2, 8.3, 8.4 ]
        spreadsheet: [ 1, 2, 3, 4, 5 ]
    name: PHP ${{ matrix.php }} PhpSpreadsheet ${{ matrix.spreadsheet }} Test on ubuntu-latest
    steps: &common_steps
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xdebug, opcache, fileinfo, gd, zip, xml, dom, ctype, iconv, simplexml, xmlreader, xmlwriter, zlib
          tools: composer:v2
          ini-values: post_max_size=256M, short_open_tag=On, opcache.enable_cli=1

      - name: System Setting
        run: |
          php -v
          composer -V
          php -m

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: |
          echo "has_deps=false" >> "$GITHUB_ENV"
          composer config --no-plugins audit.block-insecure false
          composer require phpoffice/phpspreadsheet:^${{ matrix.spreadsheet }} --no-update --prefer-stable
          composer update --prefer-stable --prefer-dist --no-interaction --no-progress
          echo "has_deps=true" >> "$GITHUB_ENV"
        continue-on-error: true

      - name: Composer Info
        if: ${{ 'true' == env.has_deps }}
        run: composer info

      - name: Run PHPUnit
        if: ${{ 'true' == env.has_deps }}
        run: composer run-script test -- -c phpunit.xml.dist --testdox

  run-macos:
    runs-on: macOS-latest
    strategy:
      max-parallel: 15
      matrix: *matrix
    name: PHP ${{ matrix.php }} PhpSpreadsheet ${{ matrix.spreadsheet }} Test on macOS-latest
    steps: *common_steps

  run-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    strategy:
      max-parallel: 15
      matrix: *matrix
    name: PHP ${{ matrix.php }} PhpSpreadsheet ${{ matrix.spreadsheet }} Test on windows-latest
    steps: *common_steps
